# Generated by Django 4.2.3 on 2023-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_profile_blogusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogusers',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
